Create SECURITY.md
golang-jwt/jwt pull request #171
Opened 2022-02-25 01:17 UTC by mfridman

Fixes https://github.com/golang-jwt/jwt/issues/21.

My email is public, but I cannot volunteer any of your to disclose your email. I wish there was a better way to offer a security@ email, but I also don't want us to maintain anything.

Maybe one day there will be a GitHub native solution, but until then, this is the best I got.

2022-02-25 09:10 UTC, oxisto commented
Can we create a google group mailing list or something, this is what I have seen in other projects.

2022-02-25 23:29 UTC, mfridman commented
Sounds good, I'll look into it. I mainly put up this PR as a starting point.

2022-03-16 23:56 UTC, james-d-elliott requested changes
Just noticed this in browsing, thought I'd highlight it so you don't accidentally miss it.

2022-03-16 23:56 UTC, james-d-elliott commented on SECURITY.md
> +Let's take this offile and find a solution first, this limits the potential impact as much as possible.
```suggestion
Let's take this offline and find a solution first, this limits the potential impact as much as possible.
```

2022-03-16 23:57 UTC, oxisto approved these changes

2022-05-28 14:02 UTC, oxisto commented
@mfridman any update on the mailing list? Otherwise let's merge it for now with just the GitHub contacts.

2022-05-28 16:40 UTC, mfridman commented
Ye let's do that. Afaics the mailing list may be more work on us, and I'm also not entirely sure how to properly maintain it.

If someone wants to set up and manage a mailing list I'm all for it.

2022-05-28 16:40 UTC, merged